/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CaseStudyRouteImport } from './routes/case-study'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExpertiseWebDesignRouteImport } from './routes/expertise.web-design'
import { Route as ExpertiseMobileAppRouteImport } from './routes/expertise.mobile-app'
import { Route as ExpertiseCrmErpRouteImport } from './routes/expertise.crm-erp'
import { Route as CaseStudiesVitamindAiRouteImport } from './routes/case-studies.vitamind-ai'
import { Route as CaseStudiesCredinRouteImport } from './routes/case-studies.credin'
import { Route as CaseStudiesAerosphereRouteImport } from './routes/case-studies.aerosphere'

const CaseStudyRoute = CaseStudyRouteImport.update({
  id: '/case-study',
  path: '/case-study',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpertiseWebDesignRoute = ExpertiseWebDesignRouteImport.update({
  id: '/expertise/web-design',
  path: '/expertise/web-design',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpertiseMobileAppRoute = ExpertiseMobileAppRouteImport.update({
  id: '/expertise/mobile-app',
  path: '/expertise/mobile-app',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpertiseCrmErpRoute = ExpertiseCrmErpRouteImport.update({
  id: '/expertise/crm-erp',
  path: '/expertise/crm-erp',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesVitamindAiRoute = CaseStudiesVitamindAiRouteImport.update({
  id: '/case-studies/vitamind-ai',
  path: '/case-studies/vitamind-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesCredinRoute = CaseStudiesCredinRouteImport.update({
  id: '/case-studies/credin',
  path: '/case-studies/credin',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesAerosphereRoute = CaseStudiesAerosphereRouteImport.update({
  id: '/case-studies/aerosphere',
  path: '/case-studies/aerosphere',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/case-study': typeof CaseStudyRoute
  '/case-studies/aerosphere': typeof CaseStudiesAerosphereRoute
  '/case-studies/credin': typeof CaseStudiesCredinRoute
  '/case-studies/vitamind-ai': typeof CaseStudiesVitamindAiRoute
  '/expertise/crm-erp': typeof ExpertiseCrmErpRoute
  '/expertise/mobile-app': typeof ExpertiseMobileAppRoute
  '/expertise/web-design': typeof ExpertiseWebDesignRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/case-study': typeof CaseStudyRoute
  '/case-studies/aerosphere': typeof CaseStudiesAerosphereRoute
  '/case-studies/credin': typeof CaseStudiesCredinRoute
  '/case-studies/vitamind-ai': typeof CaseStudiesVitamindAiRoute
  '/expertise/crm-erp': typeof ExpertiseCrmErpRoute
  '/expertise/mobile-app': typeof ExpertiseMobileAppRoute
  '/expertise/web-design': typeof ExpertiseWebDesignRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/case-study': typeof CaseStudyRoute
  '/case-studies/aerosphere': typeof CaseStudiesAerosphereRoute
  '/case-studies/credin': typeof CaseStudiesCredinRoute
  '/case-studies/vitamind-ai': typeof CaseStudiesVitamindAiRoute
  '/expertise/crm-erp': typeof ExpertiseCrmErpRoute
  '/expertise/mobile-app': typeof ExpertiseMobileAppRoute
  '/expertise/web-design': typeof ExpertiseWebDesignRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/case-study'
    | '/case-studies/aerosphere'
    | '/case-studies/credin'
    | '/case-studies/vitamind-ai'
    | '/expertise/crm-erp'
    | '/expertise/mobile-app'
    | '/expertise/web-design'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/case-study'
    | '/case-studies/aerosphere'
    | '/case-studies/credin'
    | '/case-studies/vitamind-ai'
    | '/expertise/crm-erp'
    | '/expertise/mobile-app'
    | '/expertise/web-design'
  id:
    | '__root__'
    | '/'
    | '/case-study'
    | '/case-studies/aerosphere'
    | '/case-studies/credin'
    | '/case-studies/vitamind-ai'
    | '/expertise/crm-erp'
    | '/expertise/mobile-app'
    | '/expertise/web-design'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CaseStudyRoute: typeof CaseStudyRoute
  CaseStudiesAerosphereRoute: typeof CaseStudiesAerosphereRoute
  CaseStudiesCredinRoute: typeof CaseStudiesCredinRoute
  CaseStudiesVitamindAiRoute: typeof CaseStudiesVitamindAiRoute
  ExpertiseCrmErpRoute: typeof ExpertiseCrmErpRoute
  ExpertiseMobileAppRoute: typeof ExpertiseMobileAppRoute
  ExpertiseWebDesignRoute: typeof ExpertiseWebDesignRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/case-study': {
      id: '/case-study'
      path: '/case-study'
      fullPath: '/case-study'
      preLoaderRoute: typeof CaseStudyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expertise/web-design': {
      id: '/expertise/web-design'
      path: '/expertise/web-design'
      fullPath: '/expertise/web-design'
      preLoaderRoute: typeof ExpertiseWebDesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expertise/mobile-app': {
      id: '/expertise/mobile-app'
      path: '/expertise/mobile-app'
      fullPath: '/expertise/mobile-app'
      preLoaderRoute: typeof ExpertiseMobileAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expertise/crm-erp': {
      id: '/expertise/crm-erp'
      path: '/expertise/crm-erp'
      fullPath: '/expertise/crm-erp'
      preLoaderRoute: typeof ExpertiseCrmErpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies/vitamind-ai': {
      id: '/case-studies/vitamind-ai'
      path: '/case-studies/vitamind-ai'
      fullPath: '/case-studies/vitamind-ai'
      preLoaderRoute: typeof CaseStudiesVitamindAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies/credin': {
      id: '/case-studies/credin'
      path: '/case-studies/credin'
      fullPath: '/case-studies/credin'
      preLoaderRoute: typeof CaseStudiesCredinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies/aerosphere': {
      id: '/case-studies/aerosphere'
      path: '/case-studies/aerosphere'
      fullPath: '/case-studies/aerosphere'
      preLoaderRoute: typeof CaseStudiesAerosphereRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CaseStudyRoute: CaseStudyRoute,
  CaseStudiesAerosphereRoute: CaseStudiesAerosphereRoute,
  CaseStudiesCredinRoute: CaseStudiesCredinRoute,
  CaseStudiesVitamindAiRoute: CaseStudiesVitamindAiRoute,
  ExpertiseCrmErpRoute: ExpertiseCrmErpRoute,
  ExpertiseMobileAppRoute: ExpertiseMobileAppRoute,
  ExpertiseWebDesignRoute: ExpertiseWebDesignRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
